### ISSUE TITLE
Geef je document een titel

### ISSUE THREAD

**Issue by zoepje** [Jason2426/the-startup-responsive-interactieve-website#1]
https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/e6420025e6a543a5f694296fd12cac5292fc157c/index.html#L7

Het is beter om dit de naam van de website te maken ipv "document".

**Comment by Jason2426** [comment]
Klopt inderdaad, was het vergeten. Thx 😄 

Oplossing : https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/173daba6b26a823852888354f49d473c8bcf3f7b/index.html#L7
