### ISSUE TITLE
tekst voor het logo

### ISSUE THREAD

**Issue by Sascha-Davidson** [Jason2426/the-startup-responsive-interactieve-website#11]
![image](https://github.com/Jason2426/the-startup-responsive-interactieve-website/assets/112861160/b7df62f1-6d0f-4af9-8de8-d979d1d338e4)

Is deze tekst deel van het project? zo nee zou ik het weg doen. Als het ja is dat zou ik het niet onzichtbaar maken. en als het alleen voor screen readers is kan je het uit je scherm zeten met de onderstaande code of het verwijderen en gebruik maken van een data-label. De eerste werkt zeker de data label heb ik zelf ook niet gebruikt zo ik kan het niet beloven dat het werkt
```css
.tekst{
    possition: absolute;
    left: -500000px
}
```

**Comment by Jason2426** [comment]
Scherp gezien, ik heb het probleem als het goed is gefixed 😄 

**Oplossing** : https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/12939407d2f708d1955fa14c0a4c5ac18fb7c853/styles/style.css#L152
