### ISSUE TITLE
menu werk nog niet

### ISSUE THREAD

**Issue by Sascha-Davidson** [Jason2426/the-startup-responsive-interactieve-website#12]
dit kan je maken met `overflow-y:  auto;` Dit zorgt er wel voor dat de close button verdwijnt. Dit kan je fixen door de locatie van je close button aan te passen naar dat het binnen de nav zit een en ook met `possition: static` het aan de top vast te houden. Dit is niet de enige oplossing maar zou moeten werken.

**Comment by Jason2426** [comment]
Nu werkt het wel 😄 vergete oplossing te noteren 
**Oplossing : ??**
