### ISSUE TITLE
link to page section

### ISSUE THREAD

**Issue by Sascha-Davidson** [Jason2426/the-startup-responsive-interactieve-website#13]
![image](https://github.com/Jason2426/the-startup-responsive-interactieve-website/assets/112861160/4d47089a-0fe1-42ce-b5c5-23a0d34abe55)

Als je de link wilt veranderen naar wat wij besproken hebben kan je dit doen door de link de id mee te geven. Dan gaat hij  naar die id toe. dit ziet er dan zo uit:

```html
a href="#id"

section id="id"
```

en dan moet je op de * `	scroll-behavior: smooth;` zeten om het smooth naar je section te laten gaan.

**Comment by Jason2426** [comment]
Thanks, nice weet niet of ik het zo ga houden maar in ieder geval een goede suggestie 😄 

**Oplossing :** 
``` html 
<a href="#stepsSection" class="discover-bt">Steps of the AI Design Sprint ></a>

<section class="steps" id="stepsSection">
```
