### ISSUE TITLE
Illegal spacing in image source

### ISSUE THREAD

**Issue by DamianR2004** [Jason2426/the-startup-responsive-interactieve-website#16]
Er zit nog een space in het oproepen van je image. Volgens de W3C mag dit niet, dit is op te lossen door tussen Case en studies %20 te plaatsen. 

https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/f5e5e32fb51b5554d4bbcca08e0424970d8ff3b8/index.html#L126

Je kan deze bron eens checken: https://rocketvalidator.com/html-validation/bad-value-x-for-attribute-src-on-element-img-illegal-character-in-path-segment-space-is-not-allowed

**Comment by Jason2426** [comment]
Nice, scherp gezien en goede oplossing. Thx 😄 

**Oplossing :** https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/a9d1618af4d6006141a6b6d4a1534fd0b839691c/index.html#L153

https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/a9d1618af4d6006141a6b6d4a1534fd0b839691c/index.html#L159
