### ISSUE TITLE
Suggestie: check of je een svg kan gebruiken

### ISSUE THREAD

**Issue by DamianR2004** [Jason2426/the-startup-responsive-interactieve-website#17]
Kleine suggestie, kijk of je een svg kan gebruiken (fontawesome heeft er heel veel)  Deze SVG's  zijn beter aan te passen en laden sneller in dan een image.

https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/f5e5e32fb51b5554d4bbcca08e0424970d8ff3b8/index.html#L43

**Comment by Jason2426** [comment]
Goede suggestie, ik zal kijken of ik dit voor mijn volgende projecten kan toepassen 😄
