### ISSUE TITLE
Geen spatie in src attribuut

### ISSUE THREAD

**Issue by lemuelmgsn** [Jason2426/the-startup-responsive-interactieve-website#19]
![image](https://github.com/Jason2426/the-startup-responsive-interactieve-website/assets/144004180/6884f492-e36c-405a-b260-72451e27c7a1)

https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/f5e5e32fb51b5554d4bbcca08e0424970d8ff3b8/index.html#L126

https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/f5e5e32fb51b5554d4bbcca08e0424970d8ff3b8/index.html#L132

Je mag geen spaties in je src naam attribuut gebruiken.

Oplossing:

gebruik "-" / "_" / "." inplaats van een spatie.

**Comment by Jason2426** [comment]
Scherp gezien brudda  🤖 

**Oplossing:** https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/a9d1618af4d6006141a6b6d4a1534fd0b839691c/index.html#L153

https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/a9d1618af4d6006141a6b6d4a1534fd0b839691c/index.html#L159
