### ISSUE TITLE
H2 tag verkeerd afgesloten

### ISSUE THREAD

**Issue by Naddybs** [Jason2426/the-startup-responsive-interactieve-website#4]
https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/e6420025e6a543a5f694296fd12cac5292fc157c/index.html#L19

Je hebt een H2 tag geopend maar een H1 tag gesloten :p

**Comment by Jason2426** [comment]
Scherp gezien, thx 😄 

Oplossing : https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/173daba6b26a823852888354f49d473c8bcf3f7b/index.html#L19
