### ISSUE TITLE
ALT teksten

### ISSUE THREAD

**Issue by Naddybs** [Jason2426/the-startup-responsive-interactieve-website#8]
https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/e6420025e6a543a5f694296fd12cac5292fc157c/index.html#L42

Niet vergeten ALT teksten in te vullen

**Comment by Jason2426** [comment]
Thx, gefixt bij alle images.

Oplossing : https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/32eb607742c532a6ceb25405a0b71e90626a1497/index.html#L46

**Comment by KrijnHoetmer** [comment]
Let bij alt attributen vooral op de context. In dit geval denk ik dat deze puur decoratief zijn, en niet veel toevoegen voor iemand die ze niet kan zien. Vraag je af: 1) zou ik deze afbeelding aan de telefoon voorlezen, en 2) hoe dan? Als je 'm niet zou voorlezen, gebruik dan `alt=""`, zodat de browser weet dat die genegeerd kan worden. Zie meer info op https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images
