### ISSUE TITLE
je link element heeft naast Hreff ook imagesrcet

### ISSUE THREAD

**Issue by BibekMA** [Jason2426/the-startup-responsive-interactieve-website#9]
je hebt wel over een hreff ingevuld met #, maar nog niet alt in gevuld dus dat kun je nog doen

https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/f5e5e32fb51b5554d4bbcca08e0424970d8ff3b8/index.html#L30

**Comment by Jason2426** [comment]
Thx, ik denk zelf dat dit wel handig is maar niet persee nodig want de screenreader zal het oplezen als link en dan de text wat al denk ik voldoende is maar wel een goede tip 😄 

'f the proceeding text is a hyperlink, the screen reader will say “Link” before reading the text.'

**Eventuele oplossing :** https://github.com/Jason2426/the-startup-responsive-interactieve-website/blob/34086cb8a291e66e5b63870b2bc2d7ef75028089/index.html#L19
